apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hiburan-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-hiburan-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-hiburan-service
            port:
              number: 80